/* HR workflow module: payroll employees only. Data is stored separately in browser LocalStorage. */
const HR_KEY='unified_hr_payroll_v1';
const HR_PAGES=['hr-dashboard','hr-employees','hr-manpower','hr-recruitment','hr-attendance','hr-leave','hr-payroll','hr-separation','hr-reports'];
function hrState(){
 const empty={employees:[],manpower:[],candidates:[],attendance:[],leaves:[],payroll:[],separations:[]};
 try{
  const saved=JSON.parse(localStorage.getItem(HR_KEY))||{};
  for(const key of Object.keys(empty)) if(!Array.isArray(saved[key])) saved[key]=[];
  return {...empty,...saved};
 }catch{return empty;}
}
function hrSave(s){localStorage.setItem(HR_KEY,JSON.stringify(s))}
function hrEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hrId(prefix){return prefix+'-'+Date.now().toString().slice(-7)}
function hrTable(rows,cols,actions=false){return `<div class="section-card"><div class="hr-table-wrap"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}${actions?'<th>Action</th>':''}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td>${hrEsc(r[c[0]])}</td>`).join('')}${actions?`<td><button class="btn btn-secondary btn-sm" onclick="hrAdvance('${hrEsc(r.id)}')">${r.status==='Approved'?'Reopen':'Approve'}</button></td>`:''}</tr>`).join(''):`<tr><td colspan="${cols.length+(actions?1:0)}" style="text-align:center;color:#8792a5;padding:24px">No records yet</td></tr>`}</tbody></table></div></div>`}
function hrForm(title,fields,submitText='Save record',extra=''){
 const group=fields[0].group;
 const controls=fields.map(f=>{
   const req=f.required?'required':'';
   const label=hrEsc(f.label);
   if(f.type==='select') return `<label class="hr-field">${label}<select name="${hrEsc(f.name)}" ${req}>${(f.options||[]).map(o=>`<option value="${hrEsc(o)}">${hrEsc(o)}</option>`).join('')}</select></label>`;
   if(f.type==='checkbox') return `<label class="hr-check-field"><input name="${hrEsc(f.name)}" type="checkbox" value="true" onchange="hrToggleAccountFields(this)"> ${label}</label>`;
   return `<label class="hr-field">${label}<input name="${hrEsc(f.name)}" type="${hrEsc(f.type||'text')}" ${req} ${f.step?'step="'+hrEsc(f.step)+'"':''} ${f.placeholder?'placeholder="'+hrEsc(f.placeholder)+'"':''}></label>`;
 }).join('');
 return `<div class="section-card hr-form-card"><div class="section-head"><div><div class="section-title">${hrEsc(title)}</div><div class="hr-card-hint">Add and manage ${hrEsc(title.toLowerCase())} records.</div></div><button class="btn-primary" type="button" onclick="hrOpenModal()"><i class="ti ti-plus"></i> ${hrEsc(title)}</button></div><div class="hr-modal" id="hr-entry-modal" aria-hidden="true"><div class="hr-modal-backdrop" onclick="hrCloseModal()"></div><section class="hr-modal-panel" role="dialog" aria-modal="true" aria-label="${hrEsc(title)}"><div class="hr-modal-head"><div><h3>${hrEsc(title)}</h3><p>Enter the information below and save the record.</p></div><button type="button" class="hr-modal-close" aria-label="Close" onclick="hrCloseModal()">&times;</button></div><form class="hr-form" onsubmit="return hrSubmit(event,'${group}')"><div class="hr-form-grid">${controls}</div>${extra}<div class="hr-modal-foot"><button class="btn-secondary" type="button" onclick="hrCloseModal()">Cancel</button><button class="btn-primary" type="submit">${hrEsc(submitText)}</button></div></form></section></div></div>`;
}
function hrOpenModal(){const m=document.getElementById('hr-entry-modal');if(m){m.classList.add('is-open');m.setAttribute('aria-hidden','false');document.body.classList.add('hr-modal-open');m.querySelector('input,select')?.focus()}}
function hrToggleAccountFields(check){const box=document.getElementById('hr-account-fields');if(box)box.hidden=!check.checked;}
function hrCloseModal(){const m=document.getElementById('hr-entry-modal');if(m){m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('hr-modal-open')}}

async function hrSubmit(e,group){e.preventDefault();const s=hrState(),form=e.target,d=Object.fromEntries(new FormData(form).entries());d.id=hrId(group.slice(0,3));d.status=d.status||'Pending';if(group==='employees'){if((s.employees||[]).some(x=>String(x.employeeId||'').trim().toLowerCase()===String(d.employeeId||'').trim().toLowerCase())){alert('This Employee ID already exists.');return false;}const salary=Number(d.salary);if(!Number.isFinite(salary)||salary<0){alert('Monthly salary must be a valid non-negative amount.');return false;}d.salary=salary;d.employeeId=String(d.employeeId||'').trim();d.status='Active';d.accountStatus='No login';if(d.createAccount){const email=String(d.loginEmail||'').trim().toLowerCase(),password=String(d.initialPassword||''),role=String(d.loginRole||'');if(!email||password.length<8||!role){alert('Enter login email, select a role, and provide an initial password of at least 8 characters.');return false;}if((s.employees||[]).some(e=>String(e.loginEmail||'').toLowerCase()===email)){alert('This email is already linked to an HR employee.');return false;}try{const user=await api('/users',{method:'POST',body:JSON.stringify({name:d.name,email,password,role,active:true})});const x=db();x.users=x.users||[];if(!x.users.some(u=>String(u.id)===String(user.id)))x.users.unshift({id:user.id,name:user.name,email:user.email,role:user.role,managerId:user.managerId||null,active:user.active!==false});save(x);d.linkedUserId=user.id;d.loginEmail=email;d.accountStatus='Active';}catch(err){alert(err.message||'Could not create login account.');return false;}}delete d.createAccount;delete d.initialPassword;delete d.loginRole;}if(group==='separations'){if(s.separations.some(x=>x.employee===d.employee&&x.status!=='Completed')){alert('An open separation already exists for this employee.');return false;}d.status='Requested';d.createdAt=new Date().toISOString();}
if(group==='attendance'){if(s.attendance.some(a=>a.employee===d.employee&&a.date===d.date)){alert('Attendance has already been recorded for this employee on this date.');return false;}d.recordedAt=new Date().toISOString();}if(group==='leaves'){if(d.to<d.from){alert('Leave end date must be on or after the start date.');return false;}const start=new Date(d.from+'T00:00:00'),end=new Date(d.to+'T00:00:00');d.days=Math.round((end-start)/86400000)+1;d.status='Pending';const overlap=s.leaves.some(l=>l.employee===d.employee&&l.status!=='Rejected'&&d.from<=l.to&&d.to>=l.from);if(overlap){alert('This leave request overlaps an existing pending or approved leave for this employee.');return false;}}if(group==='payroll'){const basic=Number(d.basic),allowances=Number(d.allowances||0),deductions=Number(d.deductions||0);if(!Number.isFinite(basic)||!Number.isFinite(allowances)||!Number.isFinite(deductions)||basic<0||allowances<0||deductions<0){alert('Salary, allowances, and deductions must be valid non-negative amounts.');return false;}if(deductions>basic+allowances){alert('Deductions cannot exceed basic salary plus allowances.');return false;}if(s.payroll.some(p=>p.month===d.month&&p.employee===d.employee)){alert('A payroll entry already exists for this employee and month.');return false;}d.basic=basic;d.allowances=allowances;d.deductions=deductions;d.netPay=basic+allowances-deductions;d.status='Draft';d.createdAt=new Date().toISOString();}s[group].unshift(d);hrSave(s);renderHRPage();return false}

function hrEmployeeTable(rows){
 const roles=Object.keys(db().roles||{});
 return `<div class="section-card"><div class="hr-table-wrap"><table class="data-table"><thead><tr><th>Employee ID</th><th>Name</th><th>Department</th><th>Designation</th><th>Manager</th><th>Joining Date</th><th>Basic Salary</th><th>Login Access</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${hrEsc(r.employeeId)}</td><td>${hrEsc(r.name)}</td><td>${hrEsc(r.department)}</td><td>${hrEsc(r.designation)}</td><td>${hrEsc(r.manager)}</td><td>${hrEsc(r.joiningDate)}</td><td>${hrEsc(r.salary)}</td><td>${r.linkedUserId?'<span class="badge badge-success">Active</span>':'<span class="badge">Not Created</span>'}</td><td>${hrEsc(r.status)}</td><td><div class="hr-row-actions"><button class="btn btn-secondary btn-sm" type="button" onclick="hrViewEmployee('${hrEsc(r.id)}')">View</button><button class="btn btn-secondary btn-sm" type="button" onclick="hrEditEmployee('${hrEsc(r.id)}')">Edit</button>${r.linkedUserId?'':`<button class="btn-primary btn-sm" type="button" onclick="hrCreateLogin('${hrEsc(r.id)}')">Create Login</button>`}</div></td></tr>`).join(''):`<tr><td colspan="10" style="text-align:center;color:#8792a5;padding:24px">No employees yet</td></tr>`}</tbody></table></div></div>`;
}
function hrViewEmployee(id){const e=hrState().employees.find(x=>x.id===id);if(!e)return;alert(`Employee: ${e.name}\nEmployee ID: ${e.employeeId}\nDepartment: ${e.department}\nDesignation: ${e.designation}\nLogin: ${e.linkedUserId?'Active':'Not Created'}`)}
function hrEditEmployee(id){const e=hrState().employees.find(x=>x.id===id);if(!e)return;const fields=[['employeeId','Employee ID'],['name','Full Name'],['department','Department'],['designation','Designation'],['manager','Reporting Manager'],['joiningDate','Joining Date'],['salary','Monthly Basic Salary']];const modal=document.createElement('div');modal.className='hr-modal is-open';modal.id='hr-edit-modal';modal.innerHTML=`<div class="hr-modal-backdrop" onclick="this.parentElement.remove()"></div><section class="hr-modal-panel" role="dialog" aria-modal="true"><div class="hr-modal-head"><h3>Edit Employee</h3><button class="hr-modal-close" type="button" onclick="document.getElementById('hr-edit-modal').remove()">&times;</button></div><form class="hr-form" onsubmit="return hrSaveEmployeeEdit(event,'${hrEsc(id)}')"><div class="hr-form-grid">${fields.map(([k,label])=>`<label class="hr-field">${label}<input name="${k}" value="${hrEsc(e[k]||'')}" ${k==='salary'?'type="number" step="0.01"':k==='joiningDate'?'type="date"':''} required></label>`).join('')}</div><div class="hr-modal-foot"><button type="button" class="btn-secondary" onclick="document.getElementById('hr-edit-modal').remove()">Cancel</button><button class="btn-primary" type="submit">Save Changes</button></div></form></section>`;document.body.appendChild(modal)}
function hrSaveEmployeeEdit(ev,id){ev.preventDefault();const s=hrState(),e=s.employees.find(x=>x.id===id);if(!e)return false;const d=Object.fromEntries(new FormData(ev.target).entries()),employeeId=String(d.employeeId||'').trim(),salary=Number(d.salary);if(s.employees.some(x=>x.id!==id&&String(x.employeeId||'').trim().toLowerCase()===employeeId.toLowerCase())){alert('This Employee ID is already assigned to another employee.');return false;}if(!Number.isFinite(salary)||salary<0){alert('Monthly salary must be a valid non-negative amount.');return false;}d.employeeId=employeeId;d.salary=salary;Object.assign(e,d);hrSave(s);renderHRPage();return false}
function hrCreateLogin(id){const e=hrState().employees.find(x=>x.id===id);if(!e||e.linkedUserId){alert('This employee already has a linked login account.');return}const roles=Object.keys(db().roles||{});const modal=document.createElement('div');modal.className='hr-modal is-open';modal.id='hr-create-login-modal';modal.innerHTML=`<div class="hr-modal-backdrop" onclick="document.getElementById('hr-create-login-modal').remove()"></div><section class="hr-modal-panel" role="dialog" aria-modal="true"><div class="hr-modal-head"><div><h3>Create Login Account</h3><p>Link a system account to ${hrEsc(e.name)} (${hrEsc(e.employeeId)}).</p></div><button class="hr-modal-close" type="button" onclick="document.getElementById('hr-create-login-modal').remove()">&times;</button></div><form class="hr-form" onsubmit="return hrSubmitExistingLogin(event,'${hrEsc(id)}')"><div class="hr-form-grid"><label class="hr-field">Employee Name<input value="${hrEsc(e.name)}" disabled></label><label class="hr-field">Login Email<input name="email" type="email" value="${hrEsc(e.email||'')}" required></label><label class="hr-field">System Role<select name="role" required><option value="">Select role</option>${roles.map(r=>`<option value="${hrEsc(r)}">${hrEsc(r)}</option>`).join('')}</select></label><label class="hr-field">Initial Password<input name="password" type="password" minlength="8" autocomplete="new-password" required placeholder="At least 8 characters"></label></div><p class="hr-card-hint">The account will be linked to this existing employee record.</p><div class="hr-modal-foot"><button type="button" class="btn-secondary" onclick="document.getElementById('hr-create-login-modal').remove()">Cancel</button><button class="btn-primary" type="submit">Create Login</button></div></form></section>`;document.body.appendChild(modal)}
async function hrSubmitExistingLogin(ev,id){ev.preventDefault();const s=hrState(),e=s.employees.find(x=>x.id===id);if(!e||e.linkedUserId)return false;const d=Object.fromEntries(new FormData(ev.target).entries()),email=String(d.email||'').trim().toLowerCase();if(String(d.password||'').length<8){alert('Password must be at least 8 characters.');return false}if(s.employees.some(x=>x.id!==id&&String(x.loginEmail||'').toLowerCase()===email)){alert('This email is already linked to another HR employee.');return false}try{const user=await api('/users',{method:'POST',body:JSON.stringify({name:e.name,email,password:d.password,role:d.role,active:true})});const state=db();state.users=state.users||[];if(!state.users.some(u=>String(u.id)===String(user.id)))state.users.unshift({id:user.id,name:user.name,email:user.email,role:user.role,managerId:user.managerId||null,active:user.active!==false});save(state);e.linkedUserId=user.id;e.loginEmail=email;e.accountStatus='Active';hrSave(s);renderHRPage();}catch(err){alert(err.message||'Could not create login account.');return false}return false}

function hrAdvance(id){const s=hrState();for(const key of ['manpower','candidates','payroll']){const r=s[key].find(x=>x.id===id);if(r){r.status=r.status==='Approved'?'Pending':'Approved';hrSave(s);renderHRPage();return}}}
function hrPayrollTable(rows){return `<div class="section-card"><div class="hr-table-wrap"><table class="data-table"><thead><tr><th>Month</th><th>Employee</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Net Pay</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${hrEsc(r.month)}</td><td>${hrEsc(r.employee)}</td><td>${hrMoney(r.basic)}</td><td>${hrMoney(r.allowances)}</td><td>${hrMoney(r.deductions)}</td><td><strong>${hrMoney(r.netPay)}</strong></td><td>${hrEsc(r.status)}</td><td><div class="hr-row-actions">${r.status==='Draft'?`<button class="btn-primary btn-sm" type="button" onclick="hrSetPayrollStatus('${hrEsc(r.id)}','Approved')">Approve</button>`:r.status==='Approved'?`<button class="btn-primary btn-sm" type="button" onclick="hrSetPayrollStatus('${hrEsc(r.id)}','Paid')">Mark Paid</button>`:r.status==='Paid'?`<button class="btn-secondary btn-sm" type="button" onclick="hrPrintPayslip('${hrEsc(r.id)}')">Print Payslip</button>`:'—'}</div></td></tr>`).join(''):`<tr><td colspan="8" style="text-align:center;color:#8792a5;padding:24px">No payroll entries yet</td></tr>`}</tbody></table></div></div>`}
function hrMoney(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function hrPrintPayslip(id){const r=hrState().payroll.find(x=>x.id===id);if(!r||r.status!=='Paid'){alert('Payslips are available after payroll is marked Paid.');return;}const employee=hrState().employees.find(e=>String(r.employee||'').startsWith(String(e.employeeId)+' - '));const w=window.open('','_blank','width=800,height=900');if(!w){alert('Allow pop-ups to print the payslip.');return;}const esc=hrEsc,rows=[['Payroll Month',r.month],['Employee',r.employee],['Employee ID',employee?.employeeId||''],['Department',employee?.department||''],['Designation',employee?.designation||''],['Payment Status',r.status],['Paid On',r.paidAt?new Date(r.paidAt).toLocaleString():'']];w.document.write(`<!doctype html><html><head><title>Payslip - ${esc(r.month)}</title><meta charset="utf-8"><style>body{font:14px Arial,sans-serif;color:#172033;margin:40px}.head{border-bottom:2px solid #263b5a;padding-bottom:16px;margin-bottom:24px}h1{font-size:24px;margin:0 0 6px}.muted{color:#667085}table{width:100%;border-collapse:collapse;margin:16px 0}td,th{padding:12px;border-bottom:1px solid #e5e7eb;text-align:left}td:last-child{text-align:right}.total{font-size:18px;font-weight:bold;background:#f3f6fa}.note{margin-top:32px;color:#667085;font-size:12px}@media print{button{display:none}body{margin:18mm}}</style></head><body><div class="head"><h1>Salary Payslip</h1><div class="muted">Payroll period: ${esc(r.month)}</div></div><h3>Employee Information</h3><table>${rows.map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v||'—')}</td></tr>`).join('')}</table><h3>Salary Breakdown</h3><table><tr><th>Component</th><th>Amount</th></tr><tr><td>Basic Salary</td><td>${esc(hrMoney(r.basic))}</td></tr><tr><td>Allowances</td><td>${esc(hrMoney(r.allowances))}</td></tr><tr><td>Deductions</td><td>-${esc(hrMoney(r.deductions))}</td></tr><tr class="total"><td>Net Pay</td><td>${esc(hrMoney(r.netPay))}</td></tr></table><div class="note">Generated from the HR payroll record. This payslip is a printable record; it does not initiate or verify a bank transfer.</div><p><button onclick="window.print()">Print / Save as PDF</button></p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();}
function hrSetPayrollStatus(id,status){const s=hrState(),r=s.payroll.find(x=>x.id===id);if(!r)return;if((status==='Approved'&&r.status!=='Draft')||(status==='Paid'&&r.status!=='Approved'))return;r.status=status;r[status==='Paid'?'paidAt':'approvedAt']=new Date().toISOString();hrSave(s);renderHRPage();}
function hrLeaveTable(rows){return `<div class="section-card"><div class="hr-table-wrap"><table class="data-table"><thead><tr><th>Employee</th><th>Leave Type</th><th>From</th><th>To</th><th>Days</th><th>Reason</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${hrEsc(r.employee)}</td><td>${hrEsc(r.leaveType)}</td><td>${hrEsc(r.from)}</td><td>${hrEsc(r.to)}</td><td>${hrEsc(r.days||'')}</td><td>${hrEsc(r.reason)}</td><td>${hrEsc(r.status)}</td><td><div class="hr-row-actions">${r.status==='Pending'?`<button class="btn-primary btn-sm" type="button" onclick="hrSetLeaveStatus('${hrEsc(r.id)}','Approved')">Approve</button><button class="btn-secondary btn-sm" type="button" onclick="hrSetLeaveStatus('${hrEsc(r.id)}','Rejected')">Reject</button>`:'—'}</div></td></tr>`).join(''):`<tr><td colspan="8" style="text-align:center;color:#8792a5;padding:24px">No leave requests yet</td></tr>`}</tbody></table></div></div>`}
function hrSeparationStatus(id,status){const s=hrState(),r=s.separations.find(x=>x.id===id);if(!r||!['Requested','Approved'].includes(r.status))return;r.status=status;r.updatedAt=new Date().toISOString();if(status==='Completed'){const e=s.employees.find(x=>x.employeeId+' - '+x.name===r.employee);if(e){e.status='Separated';e.separationDate=r.lastWorkingDate;e.accountStatus=e.linkedUserId?'Disable login manually':'No login';}}hrSave(s);renderHRPage();}
function hrSeparationTable(rows){return `<div class="section-card"><div class="hr-table-wrap"><table class="data-table"><thead><tr><th>Employee</th><th>Last Working Date</th><th>Reason</th><th>Final Settlement</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${hrEsc(r.employee)}</td><td>${hrEsc(r.lastWorkingDate)}</td><td>${hrEsc(r.reason)}</td><td>${hrMoney(r.finalSettlement||0)}</td><td>${hrEsc(r.status)}</td><td><div class="hr-row-actions">${r.status==='Requested'?`<button class="btn-primary btn-sm" onclick="hrSeparationStatus('${hrEsc(r.id)}','Approved')">Approve</button>`:r.status==='Approved'?`<button class="btn-primary btn-sm" onclick="hrSeparationStatus('${hrEsc(r.id)}','Completed')">Complete Exit</button>`:'—'}</div></td></tr>`).join(''):`<tr><td colspan="6" style="text-align:center;padding:24px">No separation records yet</td></tr>`}</tbody></table></div></div>`}
function hrSetLeaveStatus(id,status){const s=hrState(),r=s.leaves.find(x=>x.id===id);if(!r||r.status!=='Pending')return;r.status=status;r.reviewedAt=new Date().toISOString();hrSave(s);renderHRPage();}
function hrHero(){return `<div class="admin-hero"><div class="admin-hero-copy"><span class="admin-eyebrow"><i class="ti ti-users"></i> HR • Payroll employees</span><h2>Human Resources <span>Employee Lifecycle</span></h2><p>Manage approved headcount, hiring, employee records and monthly payroll.</p></div></div>`}
function hrDashboard(){const s=hrState(),active=s.employees.filter(e=>e.status==='Active').length,pending=s.manpower.filter(x=>x.status!=='Approved').length,leaves=s.leaves.filter(x=>x.status!=='Approved').length,drafts=s.payroll.filter(x=>x.status!=='Approved').length;layout('hr-dashboard','HR Dashboard','Employee lifecycle and payroll operations',`<div class="hr-page"><div class="admin-hero"><div class="admin-hero-copy"><span class="admin-eyebrow">HR overview</span><h2>Human Resources Dashboard</h2><p>Employee lifecycle and payroll operations</p></div></div><div class="stats">${stat('Active Employees',active,'ti-users')}${stat('Pending Manpower',pending,'ti-user-plus')}${stat('Leave Requests',leaves,'ti-calendar-time')}${stat('Payroll Items to Review',drafts,'ti-cash')}</div><div class="section-card"><div class="section-title">HR Workflow</div><div class="admin-quick-grid"><a href="hr-manpower.html"><i class="ti ti-user-plus"></i><div><b>Manpower Requests</b><span>Request and approve headcount</span></div><i class="ti ti-arrow-up-right"></i></a><a href="hr-recruitment.html"><i class="ti ti-clipboard-list"></i><div><b>Recruitment</b><span>Track candidates and hiring</span></div><i class="ti ti-arrow-up-right"></i></a><a href="hr-employees.html"><i class="ti ti-id-badge"></i><div><b>Employees</b><span>Payroll employee directory</span></div><i class="ti ti-arrow-up-right"></i></a><a href="hr-payroll.html"><i class="ti ti-wallet"></i><div><b>Payroll</b><span>Prepare and approve payroll</span></div><i class="ti ti-arrow-up-right"></i></a></div></div></div>`)}
function hrExportPayroll(){const rows=hrState().payroll;const cols=['month','employee','basic','allowances','deductions','netPay','status'];const csv=[cols.join(','),...rows.map(r=>cols.map(k=>'"'+String(r[k]??'').replace(/"/g,'""')+'"').join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='hr-payroll-report.csv';a.click();URL.revokeObjectURL(a.href)}
function hrExportAttendance(){const rows=hrState().attendance,cols=['employee','date','attendanceStatus'];const csv=[cols.join(','),...rows.map(r=>cols.map(k=>'"'+String(r[k]??'').replace(/"/g,'""')+'"').join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='hr-attendance-report.csv';a.click();URL.revokeObjectURL(a.href)}
function hrReports(){const s=hrState(),active=s.employees.filter(e=>e.status==='Active').length,sep=s.employees.filter(e=>e.status==='Separated').length,paid=s.payroll.filter(p=>p.status==='Paid'),pending=s.leaves.filter(l=>l.status==='Pending').length,total=paid.reduce((n,p)=>n+Number(p.netPay||0),0),attendance=s.attendance,present=attendance.filter(a=>a.attendanceStatus==='Present').length,absent=attendance.filter(a=>a.attendanceStatus==='Absent').length,late=attendance.filter(a=>a.attendanceStatus==='Late').length,attendanceRate=attendance.length?Math.round(present/attendance.length*100):0;layout('hr-reports','HR Reports','Employee, attendance, leave and payroll summaries',`<div class="hr-page">${hrHero()}<div class="stats">${stat('Active Employees',active,'ti-users')}${stat('Separated Employees',sep,'ti-user-x')}${stat('Pending Leave',pending,'ti-calendar-time')}${stat('Paid Payroll Total',hrMoney(total),'ti-cash')}${stat('Attendance Rate',attendanceRate+'%','ti-calendar-check')}${stat('Present / Absent / Late',present+' / '+absent+' / '+late,'ti-clock')}</div><div class="section-card"><div class="section-head"><div><div class="section-title">Attendance Report</div><div class="hr-card-hint">Export recorded attendance entries for spreadsheet review.</div></div><button class="btn-primary" type="button" onclick="hrExportAttendance()">Export Attendance CSV</button></div>${hrTable(attendance,[['employee','Employee'],['date','Date'],['attendanceStatus','Status']])}</div><div class="section-card"><div class="section-head"><div><div class="section-title">Payroll Report</div><div class="hr-card-hint">Export payroll records as a CSV file for spreadsheet review.</div></div><button class="btn-primary" type="button" onclick="hrExportPayroll()">Export Payroll CSV</button></div>${hrPayrollTable(s.payroll)}</div></div>`)}
function renderHRPage(){const page=location.pathname.split('/').pop().replace('.html',''),s=hrState();if(page==='hr-reports'){hrReports();return}if(page==='hr-dashboard'){hrDashboard();return}const empOptions=s.employees.map(e=>e.employeeId+' - '+e.name);let title='',body='';if(page==='hr-employees'){title='Employee Management';const roles=Object.keys(db().roles||{});const accessFields=`<div id="hr-account-fields" class="hr-account-fields" hidden><div class="hr-account-title">System Login Access</div><div class="hr-form-grid"><label class="hr-field">Login Email<input name="loginEmail" type="email" placeholder="employee@company.com"></label><label class="hr-field">System Role<select name="loginRole"><option value="">Select role</option>${roles.map(r=>`<option value="${hrEsc(r)}">${hrEsc(r)}</option>`).join('')}</select></label><label class="hr-field">Initial Password<input name="initialPassword" type="password" minlength="8" autocomplete="new-password" placeholder="At least 8 characters"></label></div><p class="hr-card-hint">Login access is optional. Employees can be saved as HR-only records.</p></div>`;body=hrForm('Add Payroll Employee',[{group:'employees',label:'Employee ID',name:'employeeId',required:true},{group:'employees',label:'Full Name',name:'name',required:true},{group:'employees',label:'Department',name:'department',required:true},{group:'employees',label:'Designation',name:'designation',required:true},{group:'employees',label:'Reporting Manager',name:'manager'},{group:'employees',label:'Joining Date',name:'joiningDate',type:'date',required:true},{group:'employees',label:'Monthly Basic Salary',name:'salary',type:'number',step:'0.01',required:true},{group:'employees',label:'Create system login account',name:'createAccount',type:'checkbox'}],'Save Employee',accessFields)+hrEmployeeTable(s.employees);}
else if(page==='hr-manpower'){title='Manpower Requests';body=hrForm('Request Headcount',[{group:'manpower',label:'Department',name:'department',required:true},{group:'manpower',label:'Position / Designation',name:'position',required:true},{group:'manpower',label:'Request Type',name:'requestType',type:'select',options:['New Position','Replacement']},{group:'manpower',label:'Number of Employees',name:'count',type:'number',required:true},{group:'manpower',label:'Reason / Justification',name:'reason',required:true},{group:'manpower',label:'Requested By',name:'requestedBy',required:true}])+hrTable(s.manpower,[['department','Department'],['position','Position'],['requestType','Type'],['count','Headcount'],['reason','Justification'],['requestedBy','Requested By'],['status','Status']],true);}
else if(page==='hr-recruitment'){title='Recruitment & Onboarding';body=hrForm('Add Candidate',[{group:'candidates',label:'Candidate Name',name:'name',required:true},{group:'candidates',label:'Position',name:'position',required:true},{group:'candidates',label:'Email / Phone',name:'contact',required:true},{group:'candidates',label:'Recruitment Stage',name:'stage',type:'select',options:['Applied','Shortlisted','Interview Scheduled','Selected','Offer Issued','Hired','Rejected']}])+hrTable(s.candidates,[['name','Candidate'],['position','Position'],['contact','Contact'],['stage','Stage'],['status','Approval']]);}
else if(page==='hr-attendance'){title='Attendance';body=hrForm('Record Attendance',[{group:'attendance',label:'Employee',name:'employee',type:'select',options:empOptions,required:true},{group:'attendance',label:'Date',name:'date',type:'date',required:true},{group:'attendance',label:'Attendance Status',name:'attendanceStatus',type:'select',options:['Present','Absent','Late','Half Day','Work From Home']}])+hrTable(s.attendance,[['employee','Employee'],['date','Date'],['attendanceStatus','Status']]);}
else if(page==='hr-leave'){title='Leave Management';body=hrForm('Submit / Record Leave Request',[{group:'leaves',label:'Employee',name:'employee',type:'select',options:empOptions,required:true},{group:'leaves',label:'Leave Type',name:'leaveType',type:'select',options:['Annual','Sick','Casual','Unpaid']},{group:'leaves',label:'From',name:'from',type:'date',required:true},{group:'leaves',label:'To',name:'to',type:'date',required:true},{group:'leaves',label:'Reason',name:'reason',required:true}])+hrLeaveTable(s.leaves);}
else if(page==='hr-separation'){title='Employee Separation & Final Settlement';body=hrForm('Start Employee Separation',[{group:'separations',label:'Employee',name:'employee',type:'select',options:empOptions,required:true},{group:'separations',label:'Last Working Date',name:'lastWorkingDate',type:'date',required:true},{group:'separations',label:'Reason for Separation',name:'reason',required:true},{group:'separations',label:'Final Settlement Amount',name:'finalSettlement',type:'number',step:'0.01',required:true}])+hrSeparationTable(s.separations);}
else if(page==='hr-payroll'){title='Payroll Processing';body=hrForm('Prepare Payroll Entry',[{group:'payroll',label:'Payroll Month',name:'month',type:'month',required:true},{group:'payroll',label:'Employee',name:'employee',type:'select',options:empOptions,required:true},{group:'payroll',label:'Basic Salary',name:'basic',type:'number',step:'0.01',required:true},{group:'payroll',label:'Allowances',name:'allowances',type:'number',step:'0.01'},{group:'payroll',label:'Deductions',name:'deductions',type:'number',step:'0.01'}])+hrPayrollTable(s.payroll);}
layout(page,title,'HR • Payroll employees',`<div class="hr-page">${body}</div>`)}

