/* ===== Sales UX & workflow fixes v2 ===== */
(function(){

  // Customer table renderer was missing in V21, causing customers.html to stop
  // with ReferenceError before the page could render.
  window.customerRows = function(rows){
    const list = Array.isArray(rows) ? rows : [];
    return table(['Customer Code','Customer','Contact','Phone','Email','Category','Status','Actions'], list.map(c=>`<tr><td><b>${esc(c.code||'—')}</b></td><td><button class="link-btn" onclick="customerDetails(${Number(c.id)})">${esc(c.name||'—')}</button></td><td>${esc(c.contact||'—')}</td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td><td>${esc(c.category||'—')}</td><td>${status(c.status||'Active')}</td><td><button class="btn-sm" onclick="customerDetails(${Number(c.id)})"><i class="ti ti-eye"></i> View</button></td></tr>`).join(''));
  };

  const originalRenderCustomers = window.renderCustomers;
  window.renderCustomers = function(){
    if(!guard('sales_customers'))return; const x=sdb();
    layout('customers','Customers','Customer master data for Sales',`<div class="section-card"><div class="section-head"><div><div class="section-title">Customer List</div><div class="hint">Customers shared by Sales and Accounting</div></div><button class="btn-primary" onclick="openCustomer()"><i class="ti ti-plus"></i> Add Customer</button></div><div class="filters"><input id="cust-search" placeholder="Search customer, code, phone" oninput="filterCustomers()"></div><div id="cust-table">${customerRows(x.customers)}</div></div>`)
  };

  function editQuotation(id){
    const x=sdb(), q=x.salesQuotations.find(a=>Number(a.id)===Number(id));
    if(!q){toast('Quotation not found');return;}
    const statuses=['Draft','Sent','Accepted','Rejected','Expired'];
    openModal(`<div class="modal" id="modal"><div class="modal-box request-modal wide"><div class="modal-head"><div><h3>Edit Sales Quotation</h3><small>${esc(q.quotationNo)} — ${esc(q.customerName)}</small></div><button onclick="closeModal()">×</button></div><div class="modal-body">
      <div class="grid2"><label>Customer<select id="sq-customer">${x.customers.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(q.customerId)?'selected':''}>${esc(c.code)} — ${esc(c.name)}</option>`).join('')}</select></label>
      <label>Quotation Date<input id="sq-date" type="date" value="${esc(q.quotationDate||'')}"></label>
      <label>Valid Until<input id="sq-valid" type="date" value="${esc(q.validUntil||'')}"></label>
      <label>Status<select id="sq-status-edit">${statuses.map(s=>`<option ${q.status===s?'selected':''}>${s}</option>`).join('')}</select></label>
      <label>Payment Terms<select id="sq-terms"><option ${q.paymentTerms==='Cash'?'selected':''}>Cash</option><option ${q.paymentTerms==='15 Days'?'selected':''}>15 Days</option><option ${q.paymentTerms==='30 Days'?'selected':''}>30 Days</option><option ${q.paymentTerms==='45 Days'?'selected':''}>45 Days</option></select></label>
      <label>Delivery Terms<input id="sq-delivery" value="${esc(q.deliveryTerms||'')}" placeholder="e.g. 7 working days"></label>
      <label>Tax Type<input id="sq-taxnote" value="${esc(q.taxNote||'')}" placeholder="Sales Tax / GST / Exempt"></label></div>
      <div class="line-head"><b>Items</b><button class="btn-sm" onclick="addSalesLine()"><i class="ti ti-plus"></i> Add Item</button></div>
      <div class="line-grid-head"><span>Product</span><span>Description</span><span>Qty</span><span>Rate</span><span>Disc %</span><span>Tax %</span><span>Total</span><span></span></div>
      <div id="sales-lines">${q.items.map((i,n)=>sqItemRow(n,i)).join('')}</div>
      <div class="request-summary"><span>Quotation Total</span><strong id="sq-total">${money(q.total)}</strong></div>
      <label>Terms & Conditions<textarea id="sq-termsnote" rows="3">${esc(q.terms||'')}</textarea></label><label>Notes<textarea id="sq-notes" rows="2">${esc(q.notes||'')}</textarea></label>
    </div><div class="modal-foot"><button class="btn-secondary" onclick="closeModal()">Cancel</button><button class="btn-secondary" onclick="saveSalesQuotationEdit(${q.id})">Save Changes</button><button class="btn-primary" onclick="saveSalesQuotationEdit(${q.id},true)"><i class="ti ti-send"></i> Save & Send</button></div></div></div>`); calcSalesForm();
  }
  window.saveSalesQuotationEdit=function(id,forceSend){
    const x=sdb(),q=x.salesQuotations.find(a=>Number(a.id)===Number(id)); if(!q)return;
    const items=collectSalesLines(); if(!items.length){toast('Add at least one product');return;}
    const customer=x.customers.find(c=>Number(c.id)===Number(document.getElementById('sq-customer').value)); if(!customer){toast('Select a customer');return;}
    const oldStatus=q.status, selected=document.getElementById('sq-status-edit').value;
    q.customerId=customer.id;q.customerName=customer.name;q.customerAddress=customer.address||'';q.quotationDate=document.getElementById('sq-date').value;q.validUntil=document.getElementById('sq-valid').value||null;q.paymentTerms=document.getElementById('sq-terms').value;q.deliveryTerms=document.getElementById('sq-delivery').value.trim();q.taxNote=document.getElementById('sq-taxnote').value.trim();q.items=items;q.total=salesTotal(items);q.terms=document.getElementById('sq-termsnote').value.trim();q.notes=document.getElementById('sq-notes').value.trim();q.status=forceSend?'Sent':selected;q.updatedAt=new Date().toISOString();
    recordActivity(x,'Updated','Sales Quotations','Sales quotation '+q.quotationNo+' updated ('+oldStatus+' → '+q.status+')','Sales Quotation');save(x);closeModal();renderSalesQuotations();toast('Quotation '+q.quotationNo+' updated');setTimeout(()=>downloadSalesQuotationPdf(q.id),250);
  };
  window.editSalesQuotation=editQuotation;

  const oldSQRows=window.salesQuotationRows;
  window.salesQuotationRows=function(rows){return table(['Quotation','Customer','Date','Valid Until','Status','Total','Actions'],rows.map(q=>`<tr><td><button class="link-btn" onclick="salesQuotationDetails(${q.id})">${esc(q.quotationNo)}</button></td><td>${esc(q.customerName)}</td><td>${esc(q.quotationDate)}</td><td>${esc(q.validUntil||'—')}</td><td>${status(q.status)}</td><td>${money(q.total)}</td><td><button class="btn-sm" onclick="salesQuotationDetails(${q.id})"><i class="ti ti-eye"></i> View</button> <button class="btn-sm" onclick="editSalesQuotation(${q.id})"><i class="ti ti-edit"></i> Edit</button> <button class="btn-sm" onclick="downloadSalesQuotationPdf(${q.id})"><i class="ti ti-file-type-pdf"></i> PDF</button> ${q.status==='Sent'?`<button class="btn-sm" onclick="acceptSalesQuotation(${q.id})"><i class="ti ti-check"></i> Accept</button>`:''} ${['Draft','Sent'].includes(q.status)?`<button class="btn-sm" onclick="rejectSalesQuotation(${q.id})">Reject</button>`:''}</td></tr>`).join(''))};

  // Standalone customer payment entry page: select an open invoice, enter any amount, save, then print receipt.
  window.openStandaloneCustomerPayment=function(){
    const x=sdb(), invoices=x.customerInvoices.filter(i=>invoiceBalance(x,i)>0); if(!invoices.length){toast('No outstanding invoices available');return;}
    openModal(`<div class="modal" id="modal"><div class="modal-box request-modal"><div class="modal-head"><div><h3>Receive Customer Payment</h3><small>Record full or partial payment against an invoice</small></div><button onclick="closeModal()">×</button></div><div class="modal-body"><label>Customer Invoice<select id="cp-invoice" onchange="refreshStandalonePayment()">${invoices.map(i=>`<option value="${i.id}">${esc(i.invoiceNo)} — ${esc(i.customerName)} — Balance ${money(invoiceBalance(x,i))}</option>`).join('')}</select></label><div id="cp-payment-fields"></div></div><div class="modal-foot"><button class="btn-secondary" onclick="closeModal()">Cancel</button><button class="btn-primary" onclick="saveStandaloneCustomerPayment()"><i class="ti ti-device-floppy"></i> Save Payment</button></div></div></div>`);refreshStandalonePayment();
  };
  window.refreshStandalonePayment=function(){const x=sdb(),i=x.customerInvoices.find(a=>Number(a.id)===Number(document.getElementById('cp-invoice')?.value));if(!i)return;const bal=invoiceBalance(x,i);document.getElementById('cp-payment-fields').innerHTML=`<div class="detail-note"><b>${esc(i.invoiceNo)} — ${esc(i.customerName)}</b><p>Invoice Total: ${money(i.amount)} | Paid: ${money(i.paidAmount)} | Outstanding: <strong>${money(bal)}</strong></p></div><div class="grid2"><label>Payment Date<input id="cp-date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Payment Amount<input id="cp-amount" type="number" min="0.01" max="${bal}" step="0.01" value="${bal}"></label><label>Method<select id="cp-method"><option>Cash</option><option>Bank Transfer</option><option>Cheque</option><option>Card</option><option>Online</option></select></label><label>Reference No.<input id="cp-ref"></label></div><label>Notes<textarea id="cp-notes" rows="2"></textarea>`};
  window.saveStandaloneCustomerPayment=function(){const id=Number(document.getElementById('cp-invoice').value);saveCustomerPayment(id)};

  window.renderSalesPayments=function(){if(!guard('sales_payments'))return;const x=sdb();layout('sales-payments','Customer Payments','Receipts and accounts receivable collections',`<div class="section-card"><div class="section-head"><div><div class="section-title">Payment Receipts</div><div class="hint">Payments received against customer invoices</div></div><button class="btn-primary" onclick="openStandaloneCustomerPayment()"><i class="ti ti-plus"></i> New Customer Payment</button></div>${paymentRows(x.customerPayments)}</div>`)};

  // Make payment save robust even when form fields are not exposed as implicit globals.
  const oldSavePayment=window.saveCustomerPayment;
  window.saveCustomerPayment=function(invoiceId){
    const x=sdb(),i=x.customerInvoices.find(a=>Number(a.id)===Number(invoiceId)); if(!i){toast('Invoice not found');return;}
    const amount=Number(document.getElementById('cp-amount')?.value||0),bal=invoiceBalance(x,i);
    if(!Number.isFinite(amount)||amount<=0||amount>bal){toast('Enter a valid payment amount up to '+money(bal));return;}
    const p={id:Date.now(),paymentNo:salesNo('REC',x.customerPayments,'paymentNo'),invoiceId:i.id,invoiceNo:i.invoiceNo,orderNo:i.orderNo,customerId:i.customerId,customerName:i.customerName,paymentDate:document.getElementById('cp-date')?.value||new Date().toISOString().slice(0,10),amount,method:document.getElementById('cp-method')?.value||'Cash',referenceNo:(document.getElementById('cp-ref')?.value||'').trim(),status:'Received',notes:(document.getElementById('cp-notes')?.value||'').trim(),createdAt:new Date().toISOString()};
    x.customerPayments.unshift(p);i.paidAmount=Number(i.paidAmount||0)+amount;i.balance=invoiceBalance(x,i);i.status=i.balance<=0?'Paid':'Partially Paid';const o=x.salesOrders.find(a=>Number(a.id)===Number(i.orderId));if(o)o.paymentStatus=i.status;recordActivity(x,'Received','Customer Payments','Payment '+p.paymentNo+' received for '+i.invoiceNo,'Customer Payment');save(x);closeModal();renderSalesPayments();toast('Payment saved successfully');setTimeout(()=>downloadCustomerPaymentPdf(p.id),250);
  };

  // Always keep the active menu item visible after a page render.
  const oldLayout=window.layout;
  window.layout=function(active,title,sub,body){oldLayout(active,title,sub,body);requestAnimationFrame(()=>{const a=document.querySelector('.nav-item.active');if(a)a.scrollIntoView({block:'nearest'});});};
})();

/* Sales workflow: CRM lead handoff, manager approval, customer response and CRM sync. */
(function(){
  function isManager(u){return u?.role==='Sales Manager'}
  function isSalesperson(u){return ['Salesperson','Sales Representative'].includes(u?.role)}
  function leadForQuote(x,q){return q?.leadId?(x.leads||[]).find(l=>String(l.id)===String(q.leadId)):null}
  function teamQuoteScope(x){const u=currentUser();let rows=x.salesQuotations||[];if(isManager(u))rows=rows.filter(q=>String(q.managerId||leadForQuote(x,q)?.managerId||'')===String(u.id));else if(isSalesperson(u))rows=rows.filter(q=>String(q.ownerId||leadForQuote(x,q)?.ownerId||'')===String(u.id));return rows}
  function syncLead(x,q,status){if(window.syncCrmLeadFromSalesQuote)window.syncCrmLeadFromSalesQuote(x,q,status)}
  function quoteStatuses(){return ['Draft','Pending Approval','Approved','Sent','Accepted','Rejected','Expired']}
  window.openSalesQuotation=function(leadId){
    const x=sdb(),u=currentUser(),lead=leadId?(x.leads||[]).find(l=>String(l.id)===String(leadId)):null;
    if(lead){if(isSalesperson(u)&&String(lead.ownerId)!==String(u.id)){toast('You can only create a quotation for your own lead');return}if(isManager(u)){toast('Sales Managers approve quotations; Salespersons create them');return}if(['Closed Won','Closed Lost'].includes(lead.stage)){toast('This lead is closed; create a new opportunity instead');return}}
    if(!x.customers.length){toast('Add a customer first');return}
    const customerId=lead?.customerId||x.customers.find(c=>c.status==='Active')?.id;
    const customer=x.customers.find(c=>Number(c.id)===Number(customerId));
    if(!customer){toast('Select a customer first');return}
    openModal(`<div class="modal" id="modal"><div class="modal-box request-modal wide"><div class="modal-head"><div><h3>New Sales Quotation</h3><small>${lead?'CRM handoff: '+esc(lead.customerName)+' · Lead #'+esc(String(lead.id)):'Prepare a quotation for customer approval'}</small></div><button onclick="closeModal()">×</button></div><div class="modal-body"><div class="grid2"><label>Customer<select id="sq-customer" ${lead?'disabled':''}>${x.customers.filter(c=>c.status==='Active').map(c=>`<option value="${c.id}" ${Number(c.id)===Number(customerId)?'selected':''}>${esc(c.code)} — ${esc(c.name)}</option>`).join('')}</select></label><label>Quotation Date<input id="sq-date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Valid Until<input id="sq-valid" type="date"></label><label>Payment Terms<select id="sq-terms"><option>Cash</option><option>15 Days</option><option>30 Days</option><option>45 Days</option></select></label><label>Delivery Terms<input id="sq-delivery" placeholder="e.g. 7 working days"></label><label>Tax Type<input id="sq-taxnote" value="${esc(salesTaxLabel())}" placeholder="Sales Tax / GST / Exempt"></label>${lead?`<label>CRM Lead<input value="#${esc(String(lead.id))} — ${esc(lead.customerName)}" disabled></label><label>Salesperson<input value="${esc((x.users||[]).find(a=>String(a.id)===String(lead.ownerId))?.name||'') }" disabled></label>`:''}</div><div class="line-head"><b>Items</b><button class="btn-sm" onclick="addSalesLine()"><i class="ti ti-plus"></i> Add Item</button></div><div class="line-grid-head"><span>Product</span><span>Description</span><span>Qty</span><span>Rate</span><span>Disc %</span><span>${esc(salesTaxLabel())} %</span><span>Total</span><span></span></div><div id="sales-lines">${sqItemRow(0,{})}</div><div class="request-summary"><span>Quotation Total</span><strong id="sq-total">${money(0)}</strong></div><label>Terms & Conditions<textarea id="sq-termsnote" rows="3"></textarea></label><label>Notes<textarea id="sq-notes" rows="2"></textarea></label></div><div class="modal-foot"><button class="btn-secondary" onclick="closeModal()">Cancel</button><button class="btn-primary" onclick="saveSalesQuotationWorkflow('Draft',${lead?lead.id:'null'})">Save Draft</button><button class="btn-primary" onclick="saveSalesQuotationWorkflow('Pending Approval',${lead?lead.id:'null'})"><i class="ti ti-send"></i> Submit for Approval</button></div></div></div>`);calcSalesForm();
  };
  window.saveSalesQuotationWorkflow=function(targetStatus,leadId){
    const x=sdb(),u=currentUser(),items=collectSalesLines();if(!items.length){toast('Add at least one product');return}
    const customer=x.customers.find(c=>Number(c.id)===Number(document.getElementById('sq-customer').value));if(!customer){toast('Select a customer');return}
    const lead=leadId?(x.leads||[]).find(l=>String(l.id)===String(leadId)):null;
    if(lead&&isSalesperson(u)&&String(lead.ownerId)!==String(u.id)){toast('You can only quote your own lead');return}
    const q={id:Date.now(),quotationNo:salesNo('SQ',x.salesQuotations,'quotationNo'),leadId:lead?.id||null,customerId:customer.id,customerName:customer.name,customerAddress:customer.address||'',ownerId:lead?.ownerId||u?.id||null,managerId:lead?.managerId||u?.managerId||null,quotationDate:document.getElementById('sq-date').value,validUntil:document.getElementById('sq-valid').value||null,paymentTerms:document.getElementById('sq-terms').value,deliveryTerms:document.getElementById('sq-delivery').value.trim(),taxNote:document.getElementById('sq-taxnote').value.trim(),items,total:salesTotal(items),status:targetStatus,terms:document.getElementById('sq-termsnote').value.trim(),notes:document.getElementById('sq-notes').value.trim(),createdAt:new Date().toISOString()};x.salesQuotations.unshift(q);if(lead){lead.quotationId=q.id;lead.quotationNo=q.quotationNo;lead.quotationStatus=targetStatus;lead.lastSalesUpdate=new Date().toISOString();lead.stage=targetStatus==='Draft'?'Quotation in Preparation':'Quotation Pending Approval'}recordActivity(x,'Created','Sales Quotations','Sales quotation '+q.quotationNo+' created for '+customer.name,'Sales Quotation');save(x);closeModal();renderSalesQuotations();toast(targetStatus==='Pending Approval'?'Quotation submitted for manager approval':'Quotation saved as Draft')
  };
  window.submitSalesQuotationForApproval=function(id){const x=sdb(),q=x.salesQuotations.find(a=>Number(a.id)===Number(id));if(!q)return;if(q.status!=='Draft'){toast('Only draft quotations can be submitted');return}q.status='Pending Approval';syncLead(x,q,q.status);recordActivity(x,'Submitted','Sales Quotations',q.quotationNo+' submitted for manager approval','Sales Quotation');save(x);renderSalesQuotations();toast('Quotation submitted for manager approval')};
  window.approveSalesQuotation=function(id){const x=sdb(),u=currentUser(),q=x.salesQuotations.find(a=>Number(a.id)===Number(id)),lead=leadForQuote(x,q);if(!q)return;const assignedManager=String(q.managerId||lead?.managerId||'');if(!isManager(u)&&u?.role!=='Admin'){toast('Only the assigned Sales Manager or Admin can approve this quotation');return}if(isManager(u)&&assignedManager!==String(u.id)){toast('Only the assigned Sales Manager can approve this quotation');return}if(q.status!=='Pending Approval'){toast('Quotation is not pending approval');return}q.status='Approved';q.approvedBy=u.id;q.approvedByName=u.name;q.approvedAt=new Date().toISOString();syncLead(x,q,q.status);recordActivity(x,'Approved','Sales Quotations',q.quotationNo+' approved by '+u.name,'Sales Quotation');save(x);renderSalesQuotations();toast('Quotation approved')};
  window.rejectSalesQuotation=function(id){const x=sdb(),u=currentUser(),q=x.salesQuotations.find(a=>Number(a.id)===Number(id)),lead=leadForQuote(x,q);if(!q)return;if(isManager(u)){if(String(q.managerId||lead?.managerId||'')!==String(u.id)){toast('You can only reject your own team quotations');return}if(q.status!=='Pending Approval'){toast('Only pending quotations can be rejected by a manager');return}}else if(q.status!=='Draft'&&q.status!=='Sent'){toast('Quotation cannot be rejected at this stage');return}q.status='Rejected';q.rejectedBy=u?.id||null;q.rejectedAt=new Date().toISOString();syncLead(x,q,q.status);recordActivity(x,'Rejected','Sales Quotations',q.quotationNo+' rejected','Sales Quotation');save(x);renderSalesQuotations();toast('Quotation rejected')};
  window.sendSalesQuotationToCustomer=function(id){const x=sdb(),u=currentUser(),q=x.salesQuotations.find(a=>Number(a.id)===Number(id)),lead=leadForQuote(x,q);if(!q)return;if(q.status!=='Approved'){toast('Quotation must be approved before it can be sent');return}if(isManager(u)){toast('Sales Manager approves quotations; the salesperson sends it to the customer');return}if(isSalesperson(u)&&String(q.ownerId||lead?.ownerId||'')!==String(u.id)){toast('You can only send your own quotations');return}q.status='Sent';q.sentAt=new Date().toISOString();syncLead(x,q,q.status);recordActivity(x,'Sent','Sales Quotations',q.quotationNo+' sent to customer','Sales Quotation');save(x);renderSalesQuotations();toast('Quotation sent to customer')};
  window.acceptSalesQuotation=function(id){const x=sdb(),q=x.salesQuotations.find(a=>Number(a.id)===Number(id));if(!q)return;if(q.status!=='Sent'){toast('Only quotations sent to the customer can be accepted');return}q.status='Accepted';q.customerAcceptedAt=new Date().toISOString();syncLead(x,q,q.status);recordActivity(x,'Accepted','Sales Quotations',q.quotationNo+' accepted by customer','Sales Quotation');save(x);renderSalesQuotations();toast('Customer acceptance recorded. Create a Sales Order next.')};
  function salesOrderReadyQuotations(x,preferredId){let rows=teamQuoteScope(x).filter(q=>q.status==='Accepted'&&!q.orderId);if(preferredId!=null){const preferred=x.salesQuotations.find(q=>Number(q.id)===Number(preferredId));if(preferred&&preferred.status==='Accepted'&&!preferred.orderId&&!rows.some(q=>Number(q.id)===Number(preferred.id)))rows.unshift(preferred)}return rows}
  window.openSalesOrderCreateModal=function(preferredId){const x=sdb(),rows=salesOrderReadyQuotations(x,preferredId);if(!rows.length){toast('No customer-accepted quotations are available for Sales Order creation');return}const selected=preferredId!=null?rows.find(q=>Number(q.id)===Number(preferredId))||rows[0]:rows[0];const customer=x.customers.find(c=>Number(c.id)===Number(selected.customerId));const items=(selected.items||[]).map(i=>`<tr><td>${esc(i.productName||i.description||'—')}</td><td>${esc(i.description||'')}</td><td>${i.quantity||0}</td><td>${money(i.rate||0)}</td><td>${money(i.total||0)}</td></tr>`).join('');openModal(`<div class="modal" id="modal"><div class="modal-box request-modal wide"><div class="modal-head"><div><h3>Create Sales Order</h3><small>Create the order from a customer-accepted quotation</small></div><button onclick="closeModal()">×</button></div><div class="modal-body"><div class="grid2"><label>Accepted Quotation<select id="so-quotation" onchange="previewSalesOrderQuotation()">${rows.map(q=>`<option value="${q.id}" ${Number(q.id)===Number(selected.id)?'selected':''}>${esc(q.quotationNo)} — ${esc(q.customerName)} — ${money(q.total)}</option>`).join('')}</select></label><label>Order Date<input id="so-order-date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Customer<input id="so-customer" value="${esc(customer?.name||selected.customerName||'')}" disabled></label><label>Quotation No.<input id="so-quotation-no" value="${esc(selected.quotationNo||'')}" disabled></label><label>Payment Terms<input id="so-payment-terms" value="${esc(selected.paymentTerms||'')}" disabled></label><label>Delivery Terms<input id="so-delivery-terms" value="${esc(selected.deliveryTerms||'')}" disabled></label></div><div id="so-quotation-preview">${items?`<div class="line-head"><b>Quotation Items</b><span class="hint">Items are copied from the accepted quotation</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>${items}</tbody></table></div>`:''}<div class="request-summary"><span>Order Total</span><strong id="so-modal-total">${money(selected.total)}</strong></div><label>Notes<textarea id="so-notes" rows="3" placeholder="Optional sales order notes"></textarea></label></div><div class="modal-foot"><button class="btn-secondary" onclick="closeModal()">Cancel</button><button class="btn-primary" onclick="saveSalesOrderFromModal()"><i class="ti ti-check"></i> Create Sales Order</button></div></div></div>`)};
  window.previewSalesOrderQuotation=function(){const x=sdb(),id=document.getElementById('so-quotation')?.value,q=x.salesQuotations.find(a=>Number(a.id)===Number(id));if(!q)return;const c=x.customers.find(a=>Number(a.id)===Number(q.customerId));document.getElementById('so-customer').value=c?.name||q.customerName||'';document.getElementById('so-quotation-no').value=q.quotationNo||'';document.getElementById('so-payment-terms').value=q.paymentTerms||'';document.getElementById('so-delivery-terms').value=q.deliveryTerms||'';document.getElementById('so-modal-total').textContent=money(q.total);const rows=(q.items||[]).map(i=>`<tr><td>${esc(i.productName||i.description||'—')}</td><td>${esc(i.description||'')}</td><td>${i.quantity||0}</td><td>${money(i.rate||0)}</td><td>${money(i.total||0)}</td></tr>`).join('');document.getElementById('so-quotation-preview').innerHTML=`${rows?`<div class="line-head"><b>Quotation Items</b><span class="hint">Items are copied from the accepted quotation</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table></div>`:''}<div class="request-summary"><span>Order Total</span><strong id="so-modal-total">${money(q.total)}</strong></div><label>Notes<textarea id="so-notes" rows="3" placeholder="Optional sales order notes"></textarea></label>`};
  window.saveSalesOrderFromModal=function(){const x=sdb(),id=document.getElementById('so-quotation')?.value,q=x.salesQuotations.find(a=>Number(a.id)===Number(id));if(!q||q.status!=='Accepted'){toast('Select a customer-accepted quotation');return}if(q.orderId||x.salesOrders.some(o=>Number(o.quotationId)===Number(q.id))){toast('A Sales Order already exists for this quotation');closeModal();renderSalesOrders();return}const orderDate=document.getElementById('so-order-date')?.value||new Date().toISOString().slice(0,10);const order={id:Date.now(),orderNo:salesNo('SO',x.salesOrders,'orderNo'),quotationId:q.id,quotationNo:q.quotationNo,leadId:q.leadId||null,customerId:q.customerId,customerName:q.customerName,orderDate,items:structuredClone(q.items||[]),total:q.total,status:'Confirmed',deliveryStatus:'Pending',invoiceStatus:'Not Invoiced',paymentStatus:'Unpaid',paymentTerms:q.paymentTerms,deliveryTerms:q.deliveryTerms,notes:document.getElementById('so-notes')?.value.trim()||'',createdAt:new Date().toISOString()};x.salesOrders.unshift(order);q.orderId=order.id;q.orderNo=order.orderNo;recordActivity(x,'Confirmed','Sales Orders','Sales order '+order.orderNo+' created from accepted quotation '+q.quotationNo,'Sales Order');save(x);closeModal();renderSalesOrders();toast('Sales Order '+order.orderNo+' created')};
  window.createSalesOrderFromQuotation=function(id){openSalesOrderCreateModal(id)};
  window.renderSalesQuotations=function(){if(!guard('sales_quotations'))return;const x=sdb(),rows=teamQuoteScope(x),u=currentUser();layout('sales-quotations','Sales Quotations','CRM handoff → manager approval → customer response',`<div class="section-card"><div class="section-head"><div><div class="section-title">Sales Quotation List</div><div class="hint">Draft → Pending Approval → Approved → Sent → Accepted / Rejected</div></div><button class="btn-primary" onclick="openSalesQuotation()"><i class="ti ti-plus"></i> New Quotation</button></div><div class="filters"><input id="sq-search" placeholder="Search quotation, customer or lead" oninput="filterSalesQuotations()"><select id="sq-status" onchange="filterSalesQuotations()"><option value="">All Statuses</option>${quoteStatuses().map(s=>`<option>${s}</option>`).join('')}</select></div><div id="sq-table">${salesWorkflowRows(rows,u)}</div></div>`)};
  function salesWorkflowRows(rows,u){return table(['Quotation','Customer / Lead','Date','Status','Total','Actions'],rows.map(q=>{const lead=leadForQuote(db(),q),owner=(db().users||[]).find(a=>String(a.id)===String(q.ownerId||lead?.ownerId));let actions=`<button class="btn-sm" onclick="salesQuotationDetails(${q.id})"><i class="ti ti-eye"></i> View</button>`;if(q.status==='Draft'&&isSalesperson(u))actions+=` <button class="btn-sm" onclick="submitSalesQuotationForApproval(${q.id})">Submit</button>`;if(q.status==='Pending Approval'&&(isManager(u)||u?.role==='Admin'))actions+=` <button class="btn-sm" onclick="approveSalesQuotation(${q.id})">Approve</button> <button class="btn-sm" onclick="rejectSalesQuotation(${q.id})">Reject</button>`;if(q.status==='Approved'&&(isSalesperson(u)||u?.role==='Admin'))actions+=` <button class="btn-sm" onclick="sendSalesQuotationToCustomer(${q.id})">Send to Customer</button>`;if(q.status==='Sent')actions+=` <button class="btn-sm" onclick="acceptSalesQuotation(${q.id})">Customer Accepted</button> <button class="btn-sm" onclick="rejectSalesQuotation(${q.id})">Customer Rejected</button>`;if(q.status==='Accepted'&&!q.orderId)actions+=` <button class="btn-sm" onclick="openSalesOrderCreateModal(${q.id})">Create Sales Order</button>`;return `<tr><td><button class="link-btn" onclick="salesQuotationDetails(${q.id})">${esc(q.quotationNo)}</button></td><td><b>${esc(q.customerName)}</b><div class="muted">${lead?`Lead #${esc(String(lead.id))} · ${esc(owner?.name||'')}`:'Standalone quotation'}</div></td><td>${esc(q.quotationDate||'—')}</td><td>${status(q.status)}</td><td>${money(q.total)}</td><td>${actions}</td></tr>`}).join(''))}
  window.filterSalesQuotations=function(){const x=sdb(),q=(document.getElementById('sq-search')?.value||'').toLowerCase(),s=document.getElementById('sq-status')?.value||'',rows=teamQuoteScope(x).filter(a=>(!q||(a.quotationNo+' '+a.customerName+' '+(a.leadId||'')).toLowerCase().includes(q))&&(!s||a.status===s));document.getElementById('sq-table').innerHTML=salesWorkflowRows(rows,currentUser())};
  // Existing edit modal is retained for draft maintenance, but its status selector is constrained by workflow.
  const oldEdit=window.editSalesQuotation;window.editSalesQuotation=function(id){const x=sdb(),q=x.salesQuotations.find(a=>Number(a.id)===Number(id)),u=currentUser();if(q&&q.status!=='Draft'){toast('Only draft quotations can be edited');return}if(oldEdit)oldEdit(id)};
  // Deep-link from CRM: sales-quotations.html?leadId=... opens the quotation form automatically.
  function handleLeadQuery(){const p=new URLSearchParams(location.search),id=p.get('leadId');if(id&&location.pathname.endsWith('sales-quotations.html'))setTimeout(()=>openSalesQuotation(Number(id)),120)}
  window.addEventListener('DOMContentLoaded',handleLeadQuery);

  /* ===== Sales Order / Delivery / Invoice separation ===== */
  // Sales Orders only show delivery/invoice/payment status. Creation of deliveries
  // and invoices is handled from their dedicated modules.
  window.salesOrderRows=function(rows){
    return table(['Order','Customer','Date','Status','Delivery','Invoice','Payment','Total','Actions'],rows.map(o=>`<tr><td><button class="link-btn" onclick="salesOrderDetails(${o.id})">${esc(o.orderNo)}</button></td><td>${esc(o.customerName)}</td><td>${esc(o.orderDate)}</td><td>${status(o.status)}</td><td>${status(o.deliveryStatus||'Pending')}</td><td>${status(o.invoiceStatus||'Not Invoiced')}</td><td>${status(o.paymentStatus||'Unpaid')}</td><td>${money(o.total)}</td><td><button class="btn-sm" onclick="salesOrderDetails(${o.id})"><i class="ti ti-eye"></i> View</button></td></tr>`).join(''))
  };

  window.renderSalesOrders=function(){
    if(!guard('sales_orders'))return;
    const x=sdb();
    layout('sales-orders','Sales Orders','Confirmed customer orders and fulfillment',`<div class="section-card"><div class="section-head"><div><div class="section-title">Sales Order List</div><div class="hint">Confirmed customer orders created from accepted quotations</div></div><button class="btn-primary" onclick="openSalesOrderCreateModal()"><i class="ti ti-plus"></i> Create Sales Order</button></div><div class="filters"><input id="so-search" placeholder="Search order or customer" oninput="filterSalesOrders()"><select id="so-status" onchange="filterSalesOrders()"><option value="">All Statuses</option><option>Confirmed</option><option>Partially Delivered</option><option>Delivered</option><option>Completed</option><option>Cancelled</option></select></div><div id="so-table">${salesOrderRows(x.salesOrders)}</div></div>`)
  };

  window.salesOrderDetails=function(id){
    const x=sdb(),o=x.salesOrders.find(a=>Number(a.id)===Number(id));
    if(!o)return;
    openModal(`<div class="modal" id="modal"><div class="modal-box request-modal wide"><div class="modal-head"><div><h3>${esc(o.orderNo)}</h3><small>${esc(o.customerName)}</small></div><button onclick="closeModal()">×</button></div><div class="modal-body"><div class="detail-grid"><div><span>Quotation</span><b>${esc(o.quotationNo||'—')}</b></div><div><span>Order Date</span><b>${esc(o.orderDate)}</b></div><div><span>Status</span><b>${status(o.status)}</b></div><div><span>Delivery</span><b>${status(o.deliveryStatus||'Pending')}</b></div><div><span>Invoice</span><b>${status(o.invoiceStatus||'Not Invoiced')}</b></div><div><span>Payment</span><b>${status(o.paymentStatus||'Unpaid')}</b></div></div>${table(['Product','Ordered','Delivered','Remaining','Rate','Total'],o.items.map(i=>{const delivered=(x.deliveries||[]).reduce((n,d)=>n+(d.items||[]).filter(z=>Number(z.productId)===Number(i.productId)&&Number(d.orderId)===Number(o.id)).reduce((m,z)=>m+Number(z.deliveredQty||0),0),0);return `<tr><td>${esc(i.productName)}</td><td>${i.quantity}</td><td>${delivered}</td><td>${Math.max(0,Number(i.quantity)-delivered)}</td><td>${money(i.rate)}</td><td>${money(i.total)}</td></tr>`}).join(''))}<div class="request-summary"><span>Order Total</span><strong>${money(o.total)}</strong></div></div><div class="modal-foot"><button class="btn-secondary" onclick="closeModal()">Close</button></div></div></div>`)
  };

  // Dedicated Delivery page: create delivery from here, not from Sales Orders.
  window.openDelivery=function(orderId){
    const x=sdb(),o=x.salesOrders.find(a=>Number(a.id)===Number(orderId));
    if(!o)return;
    const lines=o.items.map(i=>{const rem=deliveryRemaining(x,o,i);return rem>0?`<div class="line-item delivery-line" data-product="${i.productId}"><b>${esc(i.productName)}</b><span>Ordered: ${i.quantity}</span><span>Remaining: ${rem}</span><input class="d-qty" type="number" min="0" max="${rem}" step="0.01" value="${rem}"></div>`:''}).join('');
    if(!lines){toast('This order is fully delivered');return}
    openModal(`<div class="modal" id="modal"><div class="modal-box request-modal wide"><div class="modal-head"><div><h3>Create Delivery — ${esc(o.orderNo)}</h3><small>${esc(o.customerName)}</small></div><button onclick="closeModal()">×</button></div><div class="modal-body"><div class="grid2"><label>Delivery Date<input id="d-date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Warehouse / Location<input id="d-location" placeholder="Main Warehouse"></label><label>Delivered By<input id="d-by" value="${esc(currentUser()?.name||'Admin User')}"></label><label>Delivery Challan No.<input id="d-ref" placeholder="Optional reference"></label></div><div class="items-head"><div><b>Delivery Items</b><small>Enter the quantity being dispatched now.</small></div></div>${lines}<label>Notes<textarea id="d-notes" rows="2"></textarea></label></div><div class="modal-foot"><button class="btn-secondary" onclick="closeModal()">Cancel</button><button class="btn-primary" onclick="saveDelivery(${o.id})"><i class="ti ti-check"></i> Create Delivery</button></div></div></div>`)
  };

  // Delivery creation no longer creates an invoice automatically.
  window.saveDelivery=function(orderId){
    const x=sdb(),o=x.salesOrders.find(a=>Number(a.id)===Number(orderId));
    if(!o){toast('Sales order not found');return}
    const items=[...document.querySelectorAll('.delivery-line')].map(r=>({productId:Number(r.dataset.product),productName:o.items.find(i=>Number(i.productId)===Number(r.dataset.product))?.productName||'',deliveredQty:Number(r.querySelector('.d-qty')?.value||0)})).filter(i=>i.deliveredQty>0);
    if(!items.length){toast('Enter at least one delivery quantity');return}
    for(const i of items){const oi=o.items.find(a=>Number(a.productId)===Number(i.productId));if(!oi||i.deliveredQty>deliveryRemaining(x,o,oi)){toast('Delivery exceeds remaining quantity for '+i.productName);return}}
    const d={id:Date.now(),deliveryNo:salesNo('DO',x.deliveries,'deliveryNo'),orderId:o.id,orderNo:o.orderNo,quotationId:o.quotationId,quotationNo:o.quotationNo,customerId:o.customerId,customerName:o.customerName,customerAddress:x.customers.find(c=>Number(c.id)===Number(o.customerId))?.address||'',deliveryDate:document.getElementById('d-date').value,location:document.getElementById('d-location').value.trim(),deliveredBy:document.getElementById('d-by').value.trim(),referenceNo:document.getElementById('d-ref').value.trim(),items,status:'Pending',notes:document.getElementById('d-notes').value.trim(),createdAt:new Date().toISOString()};
    x.deliveries.unshift(d);
    // Creating a delivery records the dispatch, but does not mean the customer has received it.
    // The delivery remains Pending until the user explicitly marks it Delivered.
    const deliveredQtyForOrder=(oi)=> (x.deliveries||[]).filter(dd=>Number(dd.orderId)===Number(o.id)&&dd.status==='Delivered').reduce((n,dd)=>n+(dd.items||[]).filter(ii=>Number(ii.productId)===Number(oi.productId)).reduce((m,ii)=>m+Number(ii.deliveredQty||0),0),0);
    const anyDelivered=o.items.some(i=>deliveredQtyForOrder(i)>0);
    const complete=o.items.every(i=>deliveredQtyForOrder(i)>=Number(i.quantity));
    o.deliveryStatus=complete?'Delivered':(anyDelivered?'Partially Delivered':'Pending Delivery');
    if(o.status!=='Completed'&&o.status!=='Cancelled') o.status=complete?'Delivered':(anyDelivered?'Partially Delivered':'Confirmed');
    recordActivity(x,'Created','Sales Deliveries','Delivery '+d.deliveryNo+' created for '+o.orderNo+' (pending delivery)','Delivery');
    save(x);closeModal();renderSalesDeliveries();toast('Delivery '+d.deliveryNo+' created and is pending delivery');
    setTimeout(()=>downloadDeliveryChallanPdf(d.id),200)
  };

  window.deliveryRows=function(rows){
    return table(['Delivery Challan','Order','Customer','Date','Status','Items','Actions'],rows.map(d=>`<tr><td><button class="link-btn" onclick="deliveryDetails(${d.id})">${esc(d.deliveryNo)}</button></td><td>${esc(d.orderNo)}</td><td>${esc(d.customerName)}</td><td>${esc(d.deliveryDate)}</td><td>${status(d.status||'Pending')}</td><td>${d.items.length}</td><td><button class="btn-sm" onclick="deliveryDetails(${d.id})"><i class="ti ti-eye"></i> View</button> ${d.status!=='Delivered'?`<button class="btn-sm" onclick="markDeliveryDelivered(${d.id})"><i class="ti ti-check"></i> Mark Delivered</button>`:''} <button class="btn-sm" onclick="downloadDeliveryChallanPdf(${d.id})"><i class="ti ti-file-type-pdf"></i> PDF</button></td></tr>`).join(''))
  };

  window.markDeliveryDelivered=function(id){
    const x=sdb(),d=(x.deliveries||[]).find(a=>Number(a.id)===Number(id));
    if(!d){toast('Delivery not found');return}
    if(d.status==='Delivered'){toast('Delivery is already marked Delivered');return}
    const o=x.salesOrders.find(a=>Number(a.id)===Number(d.orderId));
    d.status='Delivered';
    d.deliveredAt=new Date().toISOString();
    d.deliveredMarkedBy=currentUser()?.name||'Admin User';
    if(o){
      const deliveredQty=(oi)=>(x.deliveries||[]).filter(dd=>Number(dd.orderId)===Number(o.id)&&dd.status==='Delivered').reduce((n,dd)=>n+(dd.items||[]).filter(ii=>Number(ii.productId)===Number(oi.productId)).reduce((m,ii)=>m+Number(ii.deliveredQty||0),0),0);
      const complete=o.items.every(i=>deliveredQty(i)>=Number(i.quantity));
      const any=o.items.some(i=>deliveredQty(i)>0);
      o.deliveryStatus=complete?'Delivered':(any?'Partially Delivered':'Pending Delivery');
      if(o.status!=='Completed'&&o.status!=='Cancelled') o.status=complete?'Delivered':(any?'Partially Delivered':'Confirmed');
    }
    recordActivity(x,'Delivered','Sales Deliveries','Delivery '+d.deliveryNo+' marked Delivered','Delivery');
    save(x);renderSalesDeliveries();toast('Delivery '+d.deliveryNo+' marked Delivered');
  };

  window.deliveryDetails=function(id){
    const x=sdb(),d=(x.deliveries||[]).find(a=>Number(a.id)===Number(id));
    if(!d)return;
    const o=x.salesOrders.find(a=>Number(a.id)===Number(d.orderId));
    openModal(`<div class="modal" id="modal"><div class="modal-box request-modal wide"><div class="modal-head"><div><h3>${esc(d.deliveryNo)}</h3><small>Delivery Challan — ${esc(d.customerName)} — ${esc(d.orderNo)}</small></div><button onclick="closeModal()">×</button></div><div class="modal-body"><div class="detail-grid"><div><span>Delivery Date</span><b>${esc(d.deliveryDate)}</b></div><div><span>Customer</span><b>${esc(d.customerName)}</b></div><div><span>Sales Order</span><b>${esc(d.orderNo)}</b></div><div><span>Status</span><b>${status(d.status||'Pending')}</b></div><div><span>Location</span><b>${esc(d.location||'—')}</b></div><div><span>Delivered By</span><b>${esc(d.deliveredBy||'—')}</b></div><div><span>Reference</span><b>${esc(d.referenceNo||'—')}</b></div>${d.deliveredAt?`<div><span>Delivered At</span><b>${esc(new Date(d.deliveredAt).toLocaleString())}</b></div>`:''}</div>${table(['Product','Ordered Qty','Dispatch Qty','Rate','Discount','Tax','Line Total'],d.items.map(di=>{const oi=o?.items.find(i=>Number(i.productId)===Number(di.productId));return `<tr><td>${esc(di.productName)}</td><td>${oi?.quantity||'—'}</td><td><b>${di.deliveredQty}</b></td><td>${money(oi?.rate||0)}</td><td>${Number(oi?.discountPercent||0)}%</td><td>${Number(oi?.taxPercent||0)}%</td><td>${money(oi?calcSalesItem(di.deliveredQty,oi.rate,oi.discountPercent,oi.taxPercent).total:0)}</td></tr>`}).join(''))}${d.notes?`<div class="detail-note"><b>Notes</b><p>${esc(d.notes)}</p></div>`:''}</div><div class="modal-foot"><button class="btn-secondary" onclick="downloadDeliveryChallanPdf(${d.id})"><i class="ti ti-file-type-pdf"></i> Delivery Challan PDF</button>${d.status!=='Delivered'?`<button class="btn-primary" onclick="closeModal();markDeliveryDelivered(${d.id})"><i class="ti ti-check"></i> Mark Delivered</button>`:''}<button class="btn-secondary" onclick="closeModal()">Close</button></div></div></div>`);
  };

  window.renderSalesDeliveries=function(){
    if(!guard('sales_deliveries'))return;
    const x=sdb();
    const eligible=x.salesOrders.filter(o=>!['Cancelled','Completed'].includes(o.status)&&o.items?.some(i=>deliveryRemaining(x,o,i)>0));
    layout('sales-deliveries','Deliveries','Dispatch and customer delivery management',`<div class="section-card"><div class="section-head"><div><div class="section-title">Delivery List</div><div class="hint">Goods dispatched against Sales Orders</div></div><button class="btn-primary" onclick="openDeliveryCreateModal()"><i class="ti ti-plus"></i> Create Delivery</button></div>${deliveryRows(x.deliveries)}</div>`)
  };

  window.openDeliveryCreateModal=function(preferredOrderId){
    const x=sdb(),orders=x.salesOrders.filter(o=>!['Cancelled','Completed'].includes(o.status)&&o.items?.some(i=>deliveryRemaining(x,o,i)>0));
    if(!orders.length){toast('No Sales Orders are available for delivery');return}
    const selected=preferredOrderId!=null?orders.find(o=>Number(o.id)===Number(preferredOrderId))||orders[0]:orders[0];
    openDelivery(selected.id)
  };

  // Dedicated Invoice page: create invoice from here, not from Sales Orders or Delivery.
  window.createInvoiceFromOrderModal=function(preferredOrderId){
    const x=sdb(),orders=x.salesOrders.filter(o=>!['Cancelled'].includes(o.status)&&!x.customerInvoices.some(i=>Number(i.orderId)===Number(o.id)&&i.status!=='Cancelled'));
    if(!orders.length){toast('No Sales Orders are available for invoicing');return}
    const selected=preferredOrderId!=null?orders.find(o=>Number(o.id)===Number(preferredOrderId))||orders[0]:orders[0];
    const items=(selected.items||[]).map(i=>`<tr><td>${esc(i.productName||'')}</td><td>${esc(i.description||'')}</td><td>${i.quantity||0}</td><td>${money(i.rate||0)}</td><td>${money(i.total||0)}</td></tr>`).join('');
    openModal(`<div class="modal" id="modal"><div class="modal-box request-modal wide"><div class="modal-head"><div><h3>Create Customer Invoice</h3><small>Create an invoice from a Sales Order</small></div><button onclick="closeModal()">×</button></div><div class="modal-body"><div class="grid2"><label>Sales Order<select id="inv-order" onchange="previewInvoiceOrder()">${orders.map(o=>`<option value="${o.id}" ${Number(o.id)===Number(selected.id)?'selected':''}>${esc(o.orderNo)} — ${esc(o.customerName)} — ${money(o.total)}</option>`).join('')}</select></label><label>Invoice Date<input id="inv-date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Due Date<input id="inv-due" type="date" value="${new Date(Date.now()+30*86400000).toISOString().slice(0,10)}"></label><label>Payment Terms<input id="inv-payment-terms" value="${esc(selected.paymentTerms||'Cash')}" disabled></label></div><div id="inv-preview"><div class="detail-grid"><div><span>Customer</span><b>${esc(selected.customerName)}</b></div><div><span>Order</span><b>${esc(selected.orderNo)}</b></div></div>${items?`<div class="line-head"><b>Invoice Items</b></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>${items}</tbody></table></div>`:''}<div class="request-summary"><span>Invoice Total</span><strong id="inv-modal-total">${money(selected.total)}</strong></div></div><label>Notes<textarea id="inv-notes" rows="3" placeholder="Optional invoice notes"></textarea></label></div><div class="modal-foot"><button class="btn-secondary" onclick="closeModal()">Cancel</button><button class="btn-primary" onclick="saveInvoiceFromOrderModal()"><i class="ti ti-check"></i> Create Invoice</button></div></div></div>`)
  };

  window.previewInvoiceOrder=function(){
    const x=sdb(),id=document.getElementById('inv-order')?.value,o=x.salesOrders.find(a=>Number(a.id)===Number(id));
    if(!o)return;
    document.getElementById('inv-payment-terms').value=o.paymentTerms||'Cash';
    document.getElementById('inv-modal-total').textContent=money(o.total);
    const items=(o.items||[]).map(i=>`<tr><td>${esc(i.productName||'')}</td><td>${esc(i.description||'')}</td><td>${i.quantity||0}</td><td>${money(i.rate||0)}</td><td>${money(i.total||0)}</td></tr>`).join('');
    document.getElementById('inv-preview').innerHTML=`<div class="detail-grid"><div><span>Customer</span><b>${esc(o.customerName)}</b></div><div><span>Order</span><b>${esc(o.orderNo)}</b></div></div>${items?`<div class="line-head"><b>Invoice Items</b></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>${items}</tbody></table></div>`:''}<div class="request-summary"><span>Invoice Total</span><strong id="inv-modal-total">${money(o.total)}</strong></div>`
  };

  window.saveInvoiceFromOrderModal=function(){
    const x=sdb(),id=document.getElementById('inv-order')?.value,o=x.salesOrders.find(a=>Number(a.id)===Number(id));
    if(!o){toast('Select a Sales Order');return}
    if(x.customerInvoices.some(i=>Number(i.orderId)===Number(o.id)&&i.status!=='Cancelled')){toast('Invoice already exists for this order');closeModal();renderSalesInvoices();return}
    const amount=Number(o.total||0);if(amount<=0){toast('Sales Order total must be greater than zero');return}
    const inv={id:Date.now(),invoiceNo:salesNo('INV',x.customerInvoices,'invoiceNo'),orderId:o.id,orderNo:o.orderNo,quotationId:o.quotationId,quotationNo:o.quotationNo,customerId:o.customerId,customerName:o.customerName,invoiceDate:document.getElementById('inv-date').value,dueDate:document.getElementById('inv-due').value,amount,status:'Posted',paidAmount:0,balance:amount,paymentTerms:o.paymentTerms||'Cash',items:structuredClone(o.items||[]),notes:document.getElementById('inv-notes')?.value.trim()||'',createdAt:new Date().toISOString()};
    x.customerInvoices.unshift(inv);o.invoiceStatus='Invoiced';recordActivity(x,'Posted','Customer Invoices','Invoice '+inv.invoiceNo+' created for '+o.orderNo,'Customer Invoice');save(x);closeModal();renderSalesInvoices();toast('Invoice '+inv.invoiceNo+' created');setTimeout(()=>downloadSalesInvoicePdf(inv.id),250)
  };

  window.renderSalesInvoices=function(){
    if(!guard('sales_invoices'))return;
    const x=sdb();
    layout('sales-invoices','Customer Invoices','Sales billing and receivables',`<div class="section-card"><div class="section-head"><div><div class="section-title">Customer Invoice List</div><div class="hint">Invoices generated from Sales Orders</div></div><button class="btn-primary" onclick="createInvoiceFromOrderModal()"><i class="ti ti-plus"></i> Create Invoice</button></div>${invoiceRows(x.customerInvoices)}</div>`)
  };
})();
